# Configuraçoes do servidor
server:
  port: 8081
  servlet:
    contextPath: /api

# Configurações da base de dados MySql
# Obs.: os valores DBSERVER, DBPORT, DBNAME, DBUSERNAME e DBPASSWORD devem estar configurados nas Variáveis de Ambiente.
spring:
  datasource:
    url: jdbc:mysql://${DBSERVER}:${DBPORT}/${DBNAME}?createDatabaseIfNotExist=true
    username: ${DBUSERNAME}
    password: ${DBPASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true